config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :conversions
  root "conversions#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/conversion.rb
class Conversion < ApplicationRecord
    after_create :set_converted_amount
    def set_converted_amount
        result = HTTParty.get("https://open.er-api.com/v6/latest/#{self.starting_currency}")

        if result['result'] != 'success'
            self.rate_limited = true
            self.save
            return
        end

        exchange_rate = result['rates'][self.final_currency]
        self.converted_amount = (self.amount * exchange_rate).round(2)
        self.save
    end

    def self.currency_codes
        result = HTTParty.get("https://open.er-api.com/v6/latest")
        result['rates'].keys.sort
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/conversions_controller.rb
class ConversionsController < ApplicationController
    def new
        @currency_codes = Conversion.currency_codes
        @conversion = Conversion.new
    end

    def create
        @conversion = Conversion.new
        @conversion.assign_attributes(conversion_params)
        @conversion.save
        if @conversion.rate_limited
            flash[:notice] = '* The conversion API has reached its rate limit, please try again in 20 mins *'
            redirect_to root_path
        elsif @conversion.rate_limited == false
            redirect_to conversion_url(@conversion)
        end
    end

    def show
        @conversion = Conversion.find(params[:id])
    end

    private

    def conversion_params
        params.require(:conversion).permit(:starting_currency, :amount, :final_currency)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/conversions/index.html.erb
<div class="blah">
    <div>
        Starting Currency:
        <%= select_tag 'Starting Currency Code', options_for_select(@currency_codes, 'USD') %>
    </div>
    <div>
        Amount:
        <%= number_field(:amount, step: '0.01')%>
    </div>
    <div>
        Final Currency:
        <%= select_tag 'Final Currency Code', options_for_select(@currency_codes, 'CAD') %>
    </div>
    <div>
        Result:
    </div>
    <button>Submit</button>
</div>

app/views/conversions/new.html.erb
<p id="notice"><%= notice %></p>

<div class='content-wrapper'>
    <div class="content">

        <h2> Currency Calculator</h2>

        <%= form_for @conversion, url: {action: "create"} do |f| %>

                <div class="field">
                    Starting Currency:
                    <%= f.select :starting_currency, @currency_codes, selected: "USD" %>
                </div>

                <div class="field">
                    Amount:
                    <%= f.number_field(:amount, step: '0.01') %>
                </div>

                <div class="field">
                    Final Currency:
                    <%= f.select :final_currency, @currency_codes, selected: "CAD" %>
                </div>

                <div>
                    <%= f.submit "Convert" %>
                </div>

        <% end %>

    </div>
</div>

app/views/conversions/show.html.erb
<div class='content-wrapper'>
    <div class="content">
        <h2>CONVERSION RESULT:</h2>

        <div><%= @conversion.starting_currency %> <%= @conversion.amount %> = <%= @conversion.final_currency %> <%= @conversion.converted_amount %></div>
        <br>
        <div class="field">Would you like to convert another currency?</div>
        <div><%= button_to "Back to conversion calculator", new_conversion_path, :method => "get" %></div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Conversions</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>